#pragma once

namespace strix { namespace net {

typedef int STRIX_NET_ERROR;

#define DEFINE_STRIX_NET_ERROR(Name, Value) const STRIX_NET_ERROR Name = Value;

// common
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_SUCCESS, 0)
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_FAILURE, 1)

// channel(1000-1999)
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_CHANNEL_RESOLVE_ADDRESS_FAILED			, 1000); ///< アドレス解決に失敗した
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_CHANNEL_CONNECT_FAILED					, 1001); ///< 接続に失敗した
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_CHANNEL_SERVER_LISTEN_FAILED				, 1002); ///< 待受に失敗した
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_CHANNEL_SERVER_ACCEPT_FAILED				, 1003); ///< 接続の受入に失敗した
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_CHANNEL_CONNECTION_CLOSED				, 1004); ///< 接続が切断された
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_CHANNEL_CONNECTION_TIMEOUT				, 1005); ///< 接続がタイムアウトした
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_CHANNEL_RECEIVE_ERROR					, 1006); ///< 受信に失敗した
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_CHANNEL_SEND_ERROR						, 1007); ///< 送信に失敗した
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_CHANNEL_INSUFFICIENT_BUFFER				, 1008); ///< バッファ不足
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_CHANNEL_BAD_FORMAT, 1009); ///< フォーマットエラー
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_CHANNEL_RECONNECT_FAILED                 , 1010); /// Re-connectable channel failed to reconnect

// ssl
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_SSL_ERROR								, 1100); ///< SSLエラー
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_SSL_HANDSHAKE_TIMEOUT					, 1101); ///< SSLハンドシェークがタイムアウトした

// license
DEFINE_STRIX_NET_ERROR(STRIX_NET_ERROR_LICENSE_VERIFICATION_FAILED				, 1200); /// License verification failed

// user definition(0x80000000-)
DEFINE_STRIX_NET_ERROR(USER_DEFINED												, 0x80000000); ///< ユーザー定義エラーの開始位置
#define DEFINE_STRIX_NET_ERROR_USER(Name, Value) DEFINE_STRIX_NET_ERROR(Name, 0x80000000 + Value)

} }
